################################################################################
# Copyright (C) 2016 Advanced Micro Devices, Inc. All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell cop-
# ies of the Software, and to permit persons to whom the Software is furnished
# to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IM-
# PLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNE-
# CTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
################################################################################

###################################################
# This file was generated by Tensile:             #
# https://github.com/ROCmSoftwarePlatform/Tensile #
###################################################


set( TensileClient_SOLUTIONS
  ${CMAKE_SOURCE_DIR}/Solutions.h
  ${CMAKE_SOURCE_DIR}/Solutions.cpp
  )
set( TensileClient_KERNELS
  ${CMAKE_SOURCE_DIR}/Kernels.h
  ${CMAKE_SOURCE_DIR}/Kernels.cpp
  )
set( TensileClient_SOURCE
  ${CMAKE_SOURCE_DIR}/SolutionMapper.h
  ${CMAKE_SOURCE_DIR}/Client.cpp
  ${CMAKE_SOURCE_DIR}/Client.h
  ${CMAKE_SOURCE_DIR}/CMakeLists.txt
  ${CMAKE_SOURCE_DIR}/DeviceStats.h
  ${CMAKE_SOURCE_DIR}/TensorUtils.h
  ${CMAKE_SOURCE_DIR}/MathTemplates.cpp
  ${CMAKE_SOURCE_DIR}/MathTemplates.h
  ${CMAKE_SOURCE_DIR}/TensileTypes.h
  ${CMAKE_SOURCE_DIR}/KernelHeader.h
  ${CMAKE_SOURCE_DIR}/ReferenceCPU.h
  ${CMAKE_SOURCE_DIR}/SolutionHelper.cpp
  ${CMAKE_SOURCE_DIR}/SolutionHelper.h
  ${CMAKE_SOURCE_DIR}/Tools.cpp
  ${CMAKE_SOURCE_DIR}/Tools.h
  )

